[update] E-Class Socket Test25 #228

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -47,9 +47,14 @@
               rm -rf EnvEdu_Server
             fi
             echo "Creating directory $PROJECT_NAME..."
-            pwd
-            ls
             sudo mkdir -p EnvEdu_Server
+            if [ -d "EnvEdu_Server" ]; then
+              echo "Directory created successfully."
+            else
+              echo "Failed to create directory."
+              exit 1
+            fi
+        
 
         - name: Make application.yml
           run: |
